[package]
name = "luma"
version = "0.2.3"
edition = "2021"
description = "Link management to organize the internet ⚡"

[dependencies]
tui = { package = "ratatui", version = "0.23", features = ["serde"]}
crossterm = "0.27"
clap = { version = "4.4", features = ["derive"] }
requestty = "0.5"

thiserror = "1"
anyhow = "1.0"

serde = { version = "1.0", features = ["derive"] }
json = {package = "serde_json", version = "1"}

vorbis_rs = "0.5"

env_logger = "0.10"
log = "0.4"

indexmap = { version = "2", features = ["serde"] }

lazy_static = "1.4"
# directories = "5.0"
# fs_extra = "1.3"
# dunce = "1.0"
# mpd = "0.1.0"
# rand = "0.8"
# glam = "0.24"
# ron = "0.8"
# dirs.workspace = true
# id3.workspace = true                # = "1"
# image.workspace = true              # = "0.24"
# include_dir.workspace = true        # = "0.7"
# lofty.workspace = true              #  = "0.12"
# regex.workspace = true              #  = "^1.5.5"
# serde_json.workspace = true         #  = "1.0"
# shellexpand.workspace = true        #  = "3"
# sysinfo.workspace = true
# unicode-width.workspace = true      #   = "^0.1.8"
# urlencoding.workspace = true        #   = "2"
# viuer = { version = "0.6", features = ["sixel"] }
# yaml-rust.workspace = true #   = "^0.4.5"
# ytd-rs.workspace = true    #   = { version = "0.1", features = ["yt-dlp"]}
# walkdir.workspace = true   #   = "2"
# wildmatch.workspace = true #   = "2"
# opml.workspace = true #   = "1"
# chrono.workspace = true #   = "^0.4.23"
# rss.workspace = true #   = "2"
# rfc822_sanitizer.workspace = true #   = "0.3"
# ahash.workspace = true #   = "^0.8"
# semver.workspace = true #   = "^1"
# escaper.workspace = true  #   = "0.1.1"
# textwrap.workspace = true #   = "0.16"
# bytes.workspace = true #   = "1"
# unicode-segmentation.workspace = true #   = "1.10"
# sanitize-filename.workspace = true #   = "0.4"
# percent-encoding.workspace = true  #   = "2.2"
# tonic.workspace = true
# reqwest.workspace = true
# reqwest = { version="0.11", features = ["stream"] }
# pretty_assertions.workspace = true # = "1"
# hound = "3.4"
# ringbuf = "0.3"
# tokio = { version = "1.31", features = ["full"] }

# no-panic = "0.1.26"

### Required to keep no panic happy on some of the simple pointer derefs
# [profile.dev]
# opt-level = 1
# lto = "thin"

[features]
