[package]
name = "lynkd"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
term_size = "0.3.2"
crossterm = "0.20.0"
rustyline = "11.0.0"
anyhow = "1.0.40"
log = "^0.4.14"
simplelog = "^0.12.1"
