[package]
name = "luma"
version = "0.1.2"
edition = "2021"
description = "⚡Rapid note management for the terminal."

[dependencies]
markdown = "1.0.0-alpha.11"
crossterm = "0.27"
rustyline = "12.0"
anyhow = "1.0"

serde = { version = "1", features = ["derive"] }
toml = "0.7"
clap = { version = "4.3", features = ["derive"] }
directories = "5.0"
fs_extra = "1.3"
dunce = "1.0"
